import '@ant-design/v5-patch-for-react-19';
import '@refinedev/antd/dist/reset.css';

import React, { Suspense } from 'react';
import { Metadata } from 'next';
import { cookies } from 'next/headers';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { useNotificationProvider } from '@refinedev/antd';
import { Refine } from '@refinedev/core';
import { RefineKbar, RefineKbarProvider } from '@refinedev/kbar';
import routerProvider from '@refinedev/nextjs-router';

import { DevtoolsProvider } from '@providers/devtools';
import { ColorModeContextProvider } from '@contexts/color-mode';
import { authProviderClient } from '@providers/auth-provider/auth-provider.client';
import { dataProvider } from '@providers/data-provider';

export const metadata: Metadata = {
    title: 'Refine',
    description: 'Generated by create refine app',
    icons: {
        icon: '/favicon.ico',
    },
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const theme = cookieStore.get('theme');
    const defaultMode = theme?.value === 'light' ? 'light' : 'dark';

    return (
        <html lang="en">
            <body>
                <Suspense>
                    <RefineKbarProvider>
                        <AntdRegistry>
                            <ColorModeContextProvider defaultMode={defaultMode}>
                                <DevtoolsProvider>
                                    <Refine
                                        routerProvider={routerProvider}
                                        authProvider={authProviderClient}
                                        dataProvider={dataProvider}
                                        notificationProvider={useNotificationProvider}
                                        options={{
                                            syncWithLocation: true,
                                            warnWhenUnsavedChanges: true,
                                            projectId: '64BVSR-vqtbDM-0z7Jfd',
                                            disableTelemetry: true,
                                        }}
                                    >
                                        {children}
                                        <RefineKbar />
                                    </Refine>
                                </DevtoolsProvider>
                            </ColorModeContextProvider>
                        </AntdRegistry>
                    </RefineKbarProvider>
                </Suspense>
            </body>
        </html>
    );
}
